# -*- coding: utf-8 -*-
"""BSc_Thesis VERO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T3B2VJId6dVb_DKBPR8-82fwBWjW4Q5o
"""

# Commented out IPython magic to ensure Python compatibility.
# FIRST CELL TO RUN EVERYTIME
# Official implementation of MedVit (Manzari et al., 2023) from github

!nvidia-smi
!git clone https://github.com/Omid-Nejati/MedViT.git
# %cd /content/MedViT
!pip install -r requirements.txt

"""# Google Drive"""

# Mounting Google Drive in order to have access
# to MyDrive where all the files and images are

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

"""# Roots"""

data_dir = "/content/drive/MyDrive/BSC THESIS ALZHEIMERS/OASIS_1_rawfiles"
EXTRACT_ROOT = "/content/drive/MyDrive/BSC THESIS ALZHEIMERS/OASIS1_extracted"
DATASET_ROOT = "/content/drive/MyDrive/BSC THESIS ALZHEIMERS/dataset"
SPLITS_DIR   = "/content/drive/MyDrive/BSC THESIS ALZHEIMERS/splits"
SAVE_DIR     = "/content/drive/MyDrive/BSC THESIS ALZHEIMERS/rq2"

"""# Imports & Install"""

!pip install nibabel SimpleITK opencv-python imageio tqdm ants --quiet

!pip install timm --quiet

# hyperparameter tuning
pip install optuna

!pip install torchview --quiet

from MedViT import MedViT
import os, shutil
from pytorch_grad_cam import GradCAM
from pytorch_grad_cam.utils.image import show_cam_on_image
from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget
import torch.optim as optim
from torch.optim.lr_scheduler import MultiStepLR
from torchview import draw_graph
import timm
import glob
import optuna
import shutil
import urllib.request
import numpy as np
import torch.nn as nn
from torchvision import models
import pandas as pd
import nibabel as nib
import SimpleITK as sitk
import ants
import cv2
import imageio
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
from tqdm import tqdm
from sklearn.model_selection import train_test_split, StratifiedKFold
from collections import Counter
import torch
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
import random
from PIL import Image
from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score, roc_auc_score)

"""# Reproducibility"""

SEED = 42

random.seed(SEED)                          # Python random
np.random.seed(SEED)                       # NumPy
torch.manual_seed(SEED)                    # PyTorch CPU
torch.cuda.manual_seed(SEED)              # PyTorch GPU
torch.cuda.manual_seed_all(SEED)          # PyTorch all GPUs
torch.backends.cudnn.deterministic = True  # ensures deterministic convolutions
torch.backends.cudnn.benchmark     = False # disables auto-tuning for reproducibility

print(f"All random seeds set to {SEED}")

# making sure GPU is connected
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

import os
os.listdir(data_dir)

# this only ran at the beginning when the files were still not saved properly
!mkdir /content/OASIS1_extracted

for f in glob.glob("/content/drive/MyDrive/BSC THESIS ALZHEIMERS/OASIS_1_rawfiles/*.tar.gz"):
    print("Extracting:", f)
    !tar -xzf "$f" -C /content/OASIS1_extracted

# Moving the extracted files to Drive permanently

if not os.path.exists(drive_extract):
    print("Copying extracted files to Drive (one-time, ~10 mins)...")
    shutil.copytree("/content/OASIS1_extracted", drive_extract)
    print("Done! Never extracting again.")
else:
    print("Already on Drive.")

# checking everything is there

dst = "/content/drive/MyDrive/BSC THESIS ALZHEIMERS/OASIS1_extracted"
discs = os.listdir(dst)
print(f"Discs saved so far: {len(discs)}")
print(sorted(discs))

os.listdir(EXTRACT_ROOT)

path = "/content/drive/MyDrive/BSC THESIS ALZHEIMERS/OASIS1_extracted/disc12/OAS1_0421_MR1/RAW"
os.listdir(path)
#gif non servono
#hdr+img = 3D image

# checking length, width, height and number of channels

mri_path = "/content/drive/MyDrive/BSC THESIS ALZHEIMERS/OASIS1_extracted/disc12/OAS1_0421_MR1/RAW/OAS1_0421_MR1_mpr-1_anon.hdr"

img = nib.load(mri_path)
data = img.get_fdata()
data.shape

"""# Clinical Values"""

# checking the clinical values

df = pd.read_excel("/content/drive/MyDrive/BSC THESIS ALZHEIMERS/oasis_cross-sectional-5708aa0a98d82080.xlsx")
df.head()

# Clinical Dementia Rating counts
df['CDR'].value_counts()

df['Age'].describe()

# NA count
df.isna().sum()

df.describe(include='all')

print("CDR value counts (including NaN):")
print(df['CDR'].value_counts(dropna=False))
print(f"\nTotal subjects: {len(df)}")
print(f"With CDR score: {df['CDR'].notna().sum()}")
print(f"Without CDR (young healthy controls): {df['CDR'].isna().sum()}")

# Binary classes separation
def cdr_to_label(cdr):
    """Binary label: CDR=0 → nondementia, CDR>0 → dementia."""
    return "nondementia" if cdr == 0 else "dementia"

"""# Labels Dictionary"""

labels = {}

"""Building a dictionary where the KEY is the subject_ID and
the VALUE is the binary class label such as: {subject_id: "dementia"/"nondementia"}"""

for _, row in df.iterrows():
    subj = row["ID"].split("_MR")[0]   # Stripping MR session suffix: "OAS1_0001_MR1" → "OAS1_0001"
    # cdr =  CDR (Clinical Dementia Rating)
    cdr  = row["CDR"]

    # The subjects with NaN as CDR value are the young healthy controls, hence treated as non-demented
    labels[subj] = "nondementia" if pd.isna(cdr) else cdr_to_label(cdr)

# Verify class balance
dementia_n    = sum(1 for v in labels.values() if v == "dementia")
nondementia_n = sum(1 for v in labels.values() if v == "nondementia")
print(f"Labels dict size: {len(labels)}")
print(f"Dementia subjects: {dementia_n}")
print(f"Non-dementia subjects: {nondementia_n}")

# Functions for preprocessing
def zscore_normalize(vol):
    """Z-score normalize a 3D MRI volume to ensure zero-mean and unit-variance intensity
    across the whole volume"""

    mean = np.mean(vol)
    std = np.std(vol)
    return (vol - mean) / (std + 1e-8)


def get_center_slices(vol, center=88, n=10):

  """Only taking 10 centered slices centered at Slice 88 because
  in Talairach space it corresponds to the hippocampal region (Saratxaga et al. (2021))"""

  start = center - n // 2
  end   = center + n // 2

  # Take everything in X and Y at depth Z=i
  # Since we want the shape to be 2D so (X,Y) and we want axial slices so Z
  return [(i, vol[:, :, i]) for i in range(start, min(end, vol.shape[2]))]

# Creating folders in which to store demented and not demented slices
DATASET_ROOT = "/content/drive/MyDrive/BSC THESIS ALZHEIMERS/dataset"
os.makedirs(f"{DATASET_ROOT}/dementia", exist_ok=True)
os.makedirs(f"{DATASET_ROOT}/nondementia", exist_ok=True)

"""# Full preprocessing pipeline"""

# Preprocessing pipeline using pre-processed t88_gfc files
# t88_gfc = preprocessed MRI volumes
# t88 = Talairach 1988 atlas space; gfc = N4 bias field (gain field) correction

t88_files_all = glob.glob(f"{EXTRACT_ROOT}/**/PROCESSED/MPRAGE/T88_111/*t88_gfc.hdr", recursive=True)

# One file per subject (exclude coronal and saggital reslices, keep main volume)
t88_files = [f for f in t88_files_all
             if not any(x in os.path.basename(f) for x in ['_cor_', '_sag_'])]

print(f"Pre-processed volumes: {len(t88_files)} ")

processed = 0
skipped   = 0

for hdr_path in tqdm(t88_files):
    filename = os.path.basename(hdr_path)
    # Example: "OAS1_0421_MR1_mpr_n4_anon_t88_gfc.hdr" split on "_MR" → take [0] "OAS1_0421"
    subj     = filename.split("_MR")[0]

    if subj not in labels:
        skipped += 1
        continue

    label = labels[subj]

    try:
        # STEP 1 — Load + RAS reorientation
        img = nib.load(hdr_path)
        img = nib.as_closest_canonical(img)
        vol = np.squeeze(img.get_fdata())

        # STEP 2 — Z-score normalization
        vol = zscore_normalize(vol)

        # STEP 3 — Extract 10 center AXIAL slices
        slices = get_center_slices(vol, center=88, n=10)

        # STEP 4 — Resize, convert to RGB scale and save to MyDrive
        for idx, sl in slices:
            sl_resized = cv2.resize(sl, (224, 224))

            # Converting z-scored float into uint8 image to save as PNG
            sl_uint8   = (255 * (sl_resized - sl_resized.min()) /
                         (sl_resized.max() - sl_resized.min() + 1e-8)).astype(np.uint8)
            sl_rgb     = np.stack([sl_uint8, sl_uint8, sl_uint8], axis=-1)

            # Saving in MyDrive in the dataset folder created beforehand
            out_path   = f"{DATASET_ROOT}/{label}/{subj}_slice_{idx:03d}.png"
            imageio.imwrite(out_path, sl_rgb)

        processed += 1

    except Exception as e:
        print(f"ERROR — {subj}: {e}")
        skipped += 1
        continue

print(f"Processed: {processed} | Skipped: {skipped}")
print(f"Dementia slices: {len(glob.glob(DATASET_ROOT+'/dementia/*.png'))}")
print(f"Non-dementia slices: {len(glob.glob(DATASET_ROOT+'/nondementia/*.png'))}")

# Count t88_gfc files across all discs
t88_all = glob.glob(f"{EXTRACT_ROOT}/**/PROCESSED/MPRAGE/T88_111/*t88_gfc.hdr", recursive=True)
t88_main = [f for f in t88_all if not any(x in os.path.basename(f) for x in ['_cor_', '_sag_'])]

print(f"Total t88_gfc files: {len(t88_main)}")

# Check which subjects are missing
t88_subjs = set(os.path.basename(f).split("_MR")[0] for f in t88_main)
all_subjs  = set(labels.keys())
missing    = all_subjs - t88_subjs

print(f"Subjects with t88_gfc:    {len(t88_subjs)}")
print(f"Subjects without t88_gfc: {len(missing)}")
print("Missing:", sorted(missing)[:10], "...")

dem = len(glob.glob(f"{DATASET_ROOT}/dementia/*.png")) // 10
non = len(glob.glob(f"{DATASET_ROOT}/nondementia/*.png")) // 10
print(f"Dementia subjects:     {dem}")
print(f"Non-dementia subjects: {non}")
print(f"Total subjects:        {dem + non}")
print(f"Class ratio:           1:{round(non/dem, 1)}")

"""## Comparison Images"""

# Image 1 for thesis raw t88_gfc vs. preprocessed

def show_preprocessing_comparison(hdr_path):
    # RAW
    raw_img = nib.load(hdr_path)
    raw = np.squeeze(raw_img.get_fdata())
    raw_slice = raw[:, :, 88]  # center slice

    # PREPROCESSED
    img = nib.as_closest_canonical(raw_img)
    vol = np.squeeze(img.get_fdata())
    vol = zscore_normalize(vol)
    proc_slice = vol[:, :, 88]

    # PLOT
    fig, axes = plt.subplots(1, 2, figsize=(10, 5))
    axes[0].imshow(raw_slice, cmap="gray")
    axes[0].set_title("Raw t88_gfc (before z-score)", fontsize=13)
    axes[0].axis("off")
    axes[1].imshow(proc_slice, cmap="gray")
    axes[1].set_title("After z-score normalization", fontsize=13)
    axes[1].axis("off")
    plt.tight_layout()
    plt.savefig("/content/drive/MyDrive/BSC THESIS ALZHEIMERS/preprocessing_comparison.png", dpi=150)
    plt.show()

# Run it
example = t88_files[0]
show_preprocessing_comparison(example)

# Image 2 for thesis - Instance of Demented vs. Non Demented brain
def preprocess_volume_for_vis(hdr_path):
    img = nib.load(hdr_path)
    img = nib.as_closest_canonical(img)
    vol = np.squeeze(img.get_fdata())
    vol = zscore_normalize(vol)
    return vol

def find_example_subjects(t88_files, labels, n=1):
    demented_paths    = []
    nondemented_paths = []
    for hdr_path in t88_files:
        filename = os.path.basename(hdr_path)
        subj = filename.split("_MR")[0]
        if subj not in labels:
            continue
        if labels[subj] == "dementia" and len(demented_paths) < n:
            demented_paths.append((subj, hdr_path))
        elif labels[subj] == "nondementia" and len(nondemented_paths) < n:
            nondemented_paths.append((subj, hdr_path))
        if len(demented_paths) == n and len(nondemented_paths) == n:
            break
    return demented_paths, nondemented_paths

def plot_dem_vs_nondem(t88_files, labels, slice_indices=[83, 88, 93]):
    demented, nondemented = find_example_subjects(t88_files, labels, n=1)
    dem_subj, dem_path = demented[0]
    non_subj, non_path = nondemented[0]

    dem_vol = preprocess_volume_for_vis(dem_path)
    non_vol = preprocess_volume_for_vis(non_path)

    fig, axes = plt.subplots(2, 3, figsize=(15, 10))

    for col, sl_idx in enumerate(slice_indices):
        axes[0, col].imshow(dem_vol[:, :, sl_idx], cmap="gray")
        axes[0, col].set_title(f"Slice {sl_idx}", fontsize=12)
        axes[0, col].axis("off")
        axes[1, col].imshow(non_vol[:, :, sl_idx], cmap="gray")
        axes[1, col].set_title(f"Slice {sl_idx}", fontsize=12)
        axes[1, col].axis("off")

    axes[0, 0].set_ylabel(f"Demented\n({dem_subj})", fontsize=13, fontweight="bold")
    axes[1, 0].set_ylabel(f"Non-Demented\n({non_subj})", fontsize=13, fontweight="bold")
    fig.suptitle("Preprocessed MRI: Demented vs Non-Demented", fontsize=15, fontweight="bold")
    plt.tight_layout()
    plt.savefig("/content/drive/MyDrive/BSC THESIS ALZHEIMERS/dem_vs_nondem.png", dpi=150)
    plt.show()

# Run it
plot_dem_vs_nondem(t88_files, labels)

"""# Train Val Test Split & Cross Validation"""

"""Subject-level Dataframe: each row = one subject"""

records = []
for class_label in ["dementia", "nondementia"]:
    png_files = glob.glob(f"{DATASET_ROOT}/{class_label}/*.png")

    # Extract unique subject IDs from filenames
    # e.g. "OAS1_0001_slice_083.png" → "OAS1_0001"
    subj_ids = list(set(os.path.basename(f).split("_slice_")[0] for f in png_files))
    for subj in subj_ids:
        records.append({"subject": subj, "label": class_label})

df_subjects = pd.DataFrame(records)

# Verify class balance at subject level
print("Subject-level class distribution:")
print(df_subjects["label"].value_counts())
print(f"Total subjects: {len(df_subjects)}")


"""70-20-10 stratified subject level split:
Stratified to preserve 1:3.3 class ratio in each split
Subject level to avoid data leakage between splits"""

# First split: 70% train, 30% valtest
train_subjs, temp_subjs = train_test_split(
    df_subjects, test_size=0.30,  # keep this
    random_state=42, stratify=df_subjects["label"]
)

# Second split: 0.67 of 30% ≈ 20% test, 10% val
val_subjs, test_subjs = train_test_split(
    temp_subjs, test_size=0.67,
    random_state=42, stratify=temp_subjs["label"]
)

print(f"\nTrain subjects: {len(train_subjs)} "
      f"({train_subjs['label'].value_counts()['dementia']} dem, "
      f"{train_subjs['label'].value_counts()['nondementia']} nondem)")
print(f"Val subjects:   {len(val_subjs)} "
      f"({val_subjs['label'].value_counts()['dementia']} dem, "
      f"{val_subjs['label'].value_counts()['nondementia']} nondem)")
print(f"Test subjects:  {len(test_subjs)} "
      f"({test_subjs['label'].value_counts()['dementia']} dem, "
      f"{test_subjs['label'].value_counts()['nondementia']} nondem)")


# Collect all the subject's slices

def get_slices_for_subjects(subject_df, dataset_root):

    """Expands a subject-level DataFrame into a flat list of slice paths and labels.
    Called separately for train, val, and test to maintain strict separation"""

    slice_paths = []
    slice_labels = []

    for _, row in subject_df.iterrows():
        subj  = row["subject"]
        label = row["label"]
        slices = glob.glob(f"{dataset_root}/{label}/{subj}_slice_*.png")

        if len(slices) == 0:
            print(f"WARNING: no slices found for {subj}")
            continue

        slice_paths.extend(slices)
        slice_labels.extend([label] * len(slices))

    return slice_paths, slice_labels

train_paths, train_labels = get_slices_for_subjects(train_subjs, DATASET_ROOT)
val_paths,   val_labels   = get_slices_for_subjects(val_subjs,   DATASET_ROOT)
test_paths,  test_labels  = get_slices_for_subjects(test_subjs,  DATASET_ROOT)

print(f"\nSlice-level counts:")
print(f"Train: {len(train_paths)} slices | "
      f"dem: {train_labels.count('dementia')} | "
      f"nondem: {train_labels.count('nondementia')}")
print(f"Val:   {len(val_paths)} slices | "
      f"dem: {val_labels.count('dementia')} | "
      f"nondem: {val_labels.count('nondementia')}")
print(f"Test:  {len(test_paths)} slices | "
      f"dem: {test_labels.count('dementia')} | "
      f"nondem: {test_labels.count('nondementia')}")

# 5-FOLD CROSS VALIDATION SETUP

"""Diagnostic block only: it prints how training subjects would be distributed across
5 folds for reference. CV was not used for training or model selection"""

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

print("\n5-Fold CV splits (on train subjects only):")
for fold, (train_idx, val_idx) in enumerate(
    skf.split(train_subjs["subject"], train_subjs["label"])
):
    fold_train = train_subjs.iloc[train_idx]
    fold_val   = train_subjs.iloc[val_idx]
    print(f"Fold {fold+1}: "
          f"train={len(fold_train)} subjects "
          f"({fold_train['label'].value_counts()['dementia']} dem) | "
          f"val={len(fold_val)} subjects "
          f"({fold_val['label'].value_counts()['dementia']} dem)")

# 5. Saving everything to MyDrive

splits_dir = "/content/drive/MyDrive/BSC THESIS ALZHEIMERS/splits"
os.makedirs(splits_dir, exist_ok=True)

train_subjs.to_csv(f"{splits_dir}/train_subjects.csv", index=False)
val_subjs.to_csv(f"{splits_dir}/val_subjects.csv",     index=False)
test_subjs.to_csv(f"{splits_dir}/test_subjects.csv",   index=False)

print("\nSplits saved to Drive.")
print("random_state=42 ensures full reproducibility.")

# Image 3 for thesis - histogram of 70-20-10 split divided by dementia and not dementia
splits = ['Train', 'Validation', 'Test']

dem_counts    = [
    train_subjs[train_subjs['label'] == 'dementia'].shape[0],
    val_subjs[val_subjs['label']     == 'dementia'].shape[0],
    test_subjs[test_subjs['label']   == 'dementia'].shape[0]
]
nondem_counts = [
    train_subjs[train_subjs['label'] == 'nondementia'].shape[0],
    val_subjs[val_subjs['label']     == 'nondementia'].shape[0],
    test_subjs[test_subjs['label']   == 'nondementia'].shape[0]
]
totals = [d + n for d, n in zip(dem_counts, nondem_counts)]

x      = np.arange(len(splits))
width  = 0.35

fig, ax = plt.subplots(figsize=(8, 5))

bars_nondem = ax.bar(x - width/2, nondem_counts, width,
                     label='Non-Dementia', color='steelblue',  alpha=0.85)
bars_dem    = ax.bar(x + width/2, dem_counts,    width,
                     label='Dementia',     color='tomato', alpha=0.85)

# Count labels on top of each bar
for bar in bars_nondem:
    ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 1,
            str(int(bar.get_height())), ha='center', va='bottom', fontsize=11)
for bar in bars_dem:
    ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 1,
            str(int(bar.get_height())), ha='center', va='bottom', fontsize=11)

# Total label above each pair
for i, total in enumerate(totals):
    ax.text(x[i], max(nondem_counts[i], dem_counts[i]) + 8,
            f'n={total}', ha='center', va='bottom',
            fontsize=10, fontweight='bold', color='dimgray')

ax.set_xticks(x)
ax.set_xticklabels(splits, fontsize=12)
ax.set_ylabel('Number of Subjects', fontsize=12)
ax.set_title('Subject-Level Dataset Splits by Class', fontsize=13, fontweight='bold')
ax.legend(fontsize=11)
ax.set_ylim(0, max(nondem_counts) + 30)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.tight_layout()
plt.savefig(
    "/content/drive/MyDrive/BSC THESIS ALZHEIMERS/dataset_split_histogram.png",
    dpi=150, bbox_inches='tight'
)
plt.show()
print("Saved to Drive.")

"""## Sex imbalanced distribution"""

# Check sex distribution in your dataset (Saratxaga et al., 2021)
print(df[['ID', 'M/F', 'CDR']].head())
print("\nSex distribution overall:")
print(df['M/F'].value_counts())

print("\nSex distribution by CDR class:")
print(df.groupby(['M/F', df['CDR'].apply(lambda x: 'dementia' if x > 0 else 'nondementia' if x == 0 else 'unknown')])['ID'].count())

"""##Stats table needed for thesis writing"""

# Table 1 for thesis of clinical values divided by CDR rating dementia or not

df['label'] = df['CDR'].apply(lambda x: 'Non-Dementia' if pd.isna(x) or x == 0 else 'Dementia')

# Filter to only subjects in your final dataset (t88_gfc: 346 subjects)
final_subj_ids = [s + "_MR1" for s in df_subjects['subject'].tolist()]
df_final = df[df['ID'].isin(final_subj_ids)]

# Compute stats per class
results = []
for label in ['Non-Dementia', 'Dementia']:
    subset = df_final[df_final['label'] == label]

    n        = len(subset)
    m        = (subset['M/F'] == 'M').sum()
    f        = (subset['M/F'] == 'F').sum()
    age_mean = subset['Age'].mean()
    age_std  = subset['Age'].std()
    cdr_mean = subset['CDR'].mean()
    cdr_std  = subset['CDR'].std()

    results.append({
        'Label':       label,
        '# Subjects':  n,
        'M':           m,
        'F':           f,
        'Age Mean':    round(age_mean, 2),
        'Age Std':     round(age_std,  2),
        'CDR Mean':    round(cdr_mean, 2) if label == 'Dementia' else 0.0,
        'CDR Std':     round(cdr_std,  2) if label == 'Dementia' else 0.0,
    })

df_table = pd.DataFrame(results)
print(df_table.to_string(index=False))

"""# Data Augmentation"""

# LABEL ENCODING
# dementia = 1, nondementia = 0
LABEL_MAP = {"dementia": 1, "nondementia": 0}

# Custom transform for Gaussian noise because not found in torchvision
class AddGaussianNoise:
    """
    mean=0, std=0.1 as per Saratxaga et al. (2021).
    """
    def __init__(self, mean=0.0, std=0.1):
        self.mean = mean
        self.std  = std

    def __call__(self, tensor):
        return tensor + torch.randn_like(tensor) * self.std + self.mean

    def __repr__(self):
        return f"AddGaussianNoise(mean={self.mean}, std={self.std})"

# ImageNet mean/std used for ResNet-18 (pretrained on ImageNet)
# and kept for MedViT (trained from scratch) for consistency
IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD  = [0.229, 0.224, 0.225]

# TRANSFORMS
train_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(degrees=15),
    transforms.RandomAffine( degrees=0, translate=(0.1, 0.1)),
    transforms.ColorJitter(brightness=0.2),
    transforms.ToTensor(),
    AddGaussianNoise(mean=0.0, std=0.1),
    transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD)
])

val_test_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD)
])

"""##Visualization of Augmentation"""

# Image 4 for thesis and poster presentation - visualization of augmentation techniques

# Reverse ImageNet normalization for visualization
def denormalize(tensor):
    mean = torch.tensor(IMAGENET_MEAN).view(3, 1, 1)
    std  = torch.tensor(IMAGENET_STD).view(3, 1, 1)
    return torch.clamp(tensor * std + mean, 0, 1)

def visualize_augmentations(dataset_root, n_examples=2):

    dem_slices    = glob.glob(f"{dataset_root}/dementia/*.png")
    nondem_slices = glob.glob(f"{dataset_root}/nondementia/*.png")

    examples = [
        ("Dementia",     random.choice(dem_slices)),
        ("Non-Dementia", random.choice(nondem_slices))
    ]

    # Individual named transforms for display
    named_transforms = [
    ("Horizontal Flip",
     transforms.Compose([
         transforms.Resize((224,224)),
         transforms.RandomHorizontalFlip(p=1.0),
         transforms.ToTensor(),
         transforms.Normalize(IMAGENET_MEAN, IMAGENET_STD)
     ])),
    ("Rotation ±10°",
     transforms.Compose([
         transforms.Resize((224,224)),
         transforms.RandomRotation(degrees=15),
         transforms.ToTensor(),
         transforms.Normalize(IMAGENET_MEAN, IMAGENET_STD)
     ])),
    ("Translation 10%",
     transforms.Compose([
         transforms.Resize((224,224)),
         transforms.RandomAffine(degrees=0, translate=(0.1, 0.1)),
         transforms.ToTensor(),
         transforms.Normalize(IMAGENET_MEAN, IMAGENET_STD)
     ])),
    ("Brightness Jitter",
     transforms.Compose([
         transforms.Resize((224,224)),
         transforms.ColorJitter(brightness=0.2),
         transforms.ToTensor(),
         transforms.Normalize(IMAGENET_MEAN, IMAGENET_STD)
     ])),
    ("Gaussian Noise",
     transforms.Compose([
         transforms.Resize((224,224)),
         transforms.ToTensor(),
         AddGaussianNoise(mean=0.0, std=0.1),
         transforms.Normalize(IMAGENET_MEAN, IMAGENET_STD)
     ])),
    ("Normalized\n(model input)",
     transforms.Compose([
         transforms.Resize((224,224)),
         transforms.ToTensor(),
         transforms.Normalize(IMAGENET_MEAN, IMAGENET_STD)
     ])),
]

    fig, axes = plt.subplots(len(examples), 7, figsize=(26, 8))
    fig.suptitle("Original vs Augmented Slices", fontsize=16, fontweight="bold", y=1.02)

    for row, (label, img_path) in enumerate(examples):
        img  = Image.open(img_path).convert("RGB")
        subj = os.path.basename(img_path).split("_slice_")[0]

        # Column 0 — original
        axes[row, 0].imshow(img, cmap="gray")
        axes[row, 0].set_title("Original", fontsize=11, fontweight="bold")
        axes[row, 0].set_ylabel(f"{label}\n({subj})", fontsize=10, fontweight="bold")
        axes[row, 0].axis("off")

        # Columns 1-5 — named augmentations
        for col, (aug_name, aug_transform) in enumerate(named_transforms):
            aug_tensor = aug_transform(img)
            aug_img    = denormalize(aug_tensor).permute(1, 2, 0).numpy()
            axes[row, col+1].imshow(aug_img, cmap="gray")
            axes[row, col+1].set_title(aug_name, fontsize=10)
            axes[row, col+1].axis("off")

    plt.tight_layout()
    plt.savefig(
        "/content/drive/MyDrive/BSC THESIS ALZHEIMERS/augmentation_visualization.png",
        dpi=150, bbox_inches="tight"
    )
    plt.show()
    print("Saved to Drive.")

visualize_augmentations(DATASET_ROOT)

"""#OASIS Pytorch Dataset"""

# Pytorch dataset
class OASISDataset(Dataset):

    # Loads .png slices
    def __init__(self, subject_df, dataset_root, transform=None):

        self.transform    = transform
        self.samples      = []  # list of (image_path, label) tuples

        for _, row in subject_df.iterrows():
            subj  = row["subject"]
            label = row["label"]

            # Get all slices for this subject
            slices = glob.glob(f"{dataset_root}/{label}/{subj}_slice_*.png")

            for slice_path in sorted(slices):
                self.samples.append((slice_path, LABEL_MAP[label]))

        print(f"Dataset loaded: {len(self.samples)} slices | "
              f"dementia: {sum(1 for _,l in self.samples if l==1)} | "
              f"nondementia: {sum(1 for _,l in self.samples if l==0)}")

    # How many images in my dataset
    def __len__(self):
        return len(self.samples)

    # Loading one sample
    def __getitem__(self, idx):

      """Returns:
      - subject ID
      - image
      - label
      to enable subject-level analysis and no data leakage between splits"""

      img_path, label = self.samples[idx]

      # Extract subject ID from filename
      subj = os.path.basename(img_path).split("_slice_")[0]

      image = Image.open(img_path).convert("RGB")
      if self.transform:
          image = self.transform(image)

      return image, torch.tensor(label, dtype=torch.long), subj

"""# Data Loader"""

# Load splits and DataLoaders for ResNet-18 (batch_size = 32)
train_subjs = pd.read_csv(f"{SPLITS_DIR}/train_subjects.csv")
val_subjs   = pd.read_csv(f"{SPLITS_DIR}/val_subjects.csv")
test_subjs  = pd.read_csv(f"{SPLITS_DIR}/test_subjects.csv")

train_dataset = OASISDataset(train_subjs, DATASET_ROOT, transform=train_transforms)
val_dataset   = OASISDataset(val_subjs,   DATASET_ROOT, transform=val_test_transforms)
test_dataset  = OASISDataset(test_subjs,  DATASET_ROOT, transform=val_test_transforms)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True, num_workers=2)
val_loader   = DataLoader(val_dataset,   batch_size=32, shuffle=False, num_workers=2)
test_loader  = DataLoader(test_dataset,  batch_size=32, shuffle=False, num_workers=2)

print(f"\nTrain batches: {len(train_loader)}")
print(f"Val batches:   {len(val_loader)}")
print(f"Test batches:  {len(test_loader)}")

# Load splits and DataLoaders for MedViT (batch_size = 8)
train_subjs = pd.read_csv(f"{SPLITS_DIR}/train_subjects.csv")
val_subjs   = pd.read_csv(f"{SPLITS_DIR}/val_subjects.csv")
test_subjs  = pd.read_csv(f"{SPLITS_DIR}/test_subjects.csv")

train_dataset = OASISDataset(train_subjs, DATASET_ROOT, transform=train_transforms)
val_dataset   = OASISDataset(val_subjs,   DATASET_ROOT, transform=val_test_transforms)
test_dataset  = OASISDataset(test_subjs,  DATASET_ROOT, transform=val_test_transforms)

train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True, num_workers=2)
val_loader   = DataLoader(val_dataset,   batch_size=8, shuffle=False, num_workers=2)
test_loader  = DataLoader(test_dataset,  batch_size=8, shuffle=False, num_workers=2)

print(f"\nTrain batches: {len(train_loader)}")
print(f"Val batches:   {len(val_loader)}")
print(f"Test batches:  {len(test_loader)}")

# Verify one batch
images, labels, subjects = next(iter(train_loader))
print(f"Batch shape: {images.shape}")
print(f"Labels:      {labels}")
print(f"Subjects:    {subjects[:5]}")

# Class weights to address class imbalance

"""Class weights computed using inverse frequency weighting forumla:
weight_class = n_total / (2*n_class)
This penalizes misclassification of the minority dementia class (n=56)
more heavily than the majority non-dementia (n=156)
addressing the 1:3.3 class imbalance in the training set"""

# Computed from training set only
n_train        = len(train_dataset)
n_dementia     = sum(1 for _, l in train_dataset.samples if l == 1)
n_nondementia  = sum(1 for _, l in train_dataset.samples if l == 0)

weight_nondem  = n_train / (2 * n_nondementia)
weight_dem     = n_train / (2 * n_dementia)

class_weights  = torch.tensor([weight_nondem, weight_dem], dtype=torch.float)
print(f"\nClass weights: nondementia={weight_nondem:.3f}, dementia={weight_dem:.3f}")

"""#Training Loop"""

# Training loop: Experiment 3 - no early stopping, 25 epochs
def train_model(model, train_loader, val_loader, criterion, optimizer,
                num_epochs=25, scheduler=None, save_path="/content/drive/MyDrive/BSC THESIS ALZHEIMERS/best4_model.pth"):


    """Trains a model for a fixed number of epochs and saves the best checkpoint.
    Compatible with OASISDataset which returns (image, label, subject)

    Args:
    model = either renset-18 or medvit
    train_loader, val_loader
    criterion = loss function
    otimizer = optimization technique (Adam)
    epochs = 1st experiment 50, 2nd experiment onwards 25
    scheduler = multistepLR

    Returns:
    Tracking history of validation and training losses and accuracies

    """

    best_val_loss = float('inf')
    history = {"train_loss": [], "val_loss": [], "train_acc": [], "val_acc": []}

    for epoch in range(num_epochs):

        # Setting the model to training mode
        model.train()
        running_loss, running_corrects = 0.0, 0

        # Perform forward-backward passes and accumulate losses and accuracies
        for inputs, labels, _ in train_loader:
            inputs, labels = inputs.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(inputs)

            _, preds = torch.max(outputs, 1)
            loss = criterion(outputs, labels)

            loss.backward()
            optimizer.step()

            running_loss += loss.item() * inputs.size(0)
            running_corrects += torch.sum(preds == labels.data)

        train_loss = running_loss / len(train_loader.dataset)
        train_acc = running_corrects.float() / len(train_loader.dataset)

        # Setting the model to evaluation mode
        model.eval()
        running_loss = 0.0
        running_corrects = 0


        # Compute the predictions and the statistics (losses, and accuracies)
        with torch.no_grad():
            for inputs, labels, _ in val_loader:
                inputs = inputs.to(device)
                labels = labels.to(device)

                outputs = model(inputs)
                _, preds = torch.max(outputs, 1)
                loss = criterion(outputs, labels)

                running_loss += loss.item() * inputs.size(0)
                running_corrects += torch.sum(preds == labels.data)

        val_loss = running_loss / len(val_loader.dataset)
        val_acc = running_corrects.float() / len(val_loader.dataset)

        history["train_loss"].append(train_loss)
        history["val_loss"].append(val_loss)
        history["train_acc"].append(train_acc.item())
        history["val_acc"].append(val_acc.item())

        print(f"Epoch [{epoch+1}/{num_epochs}]  "
              f"train loss: {train_loss:.4f}  train acc: {train_acc:.4f}  "
              f"val loss: {val_loss:.4f}  val acc: {val_acc:.4f}")

        if scheduler is not None:
            scheduler.step()

        # Save best model only
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), save_path)
            print(f"  Best model saved (val loss: {best_val_loss:.4f})")

    print("\nTraining complete.")
    return history

# Evaluation loop
def evaluate_model(model, test_loader, checkpoint_path, device):

  """Loads the best checkpoint and evaluates the model on the test set
  Returns accuracy, precision, recall, F1, and AUC """

  model.load_state_dict(torch.load(checkpoint_path, map_location=device))
  model.eval()

  all_labels = []
  all_preds  = []
  all_probs  = []   # needed for AUC

  with torch.no_grad():
      for inputs, labels, _ in test_loader:
          inputs = inputs.to(device)
          labels = labels.to(device)

          outputs = model(inputs)
          probs   = torch.softmax(outputs, dim=1)[:, 1]  # prob of dementia class
          _, preds = torch.max(outputs, 1)

          all_labels.extend(labels.cpu().numpy())
          all_preds.extend(preds.cpu().numpy())
          all_probs.extend(probs.cpu().numpy())

  acc  = accuracy_score(all_labels, all_preds)
  prec = precision_score(all_labels, all_preds, zero_division=0)
  rec  = recall_score(all_labels, all_preds, zero_division=0)
  f1   = f1_score(all_labels, all_preds, zero_division=0)
  auc  = roc_auc_score(all_labels, all_probs)

  print("=" * 45)
  print(f"  Accuracy:  {acc:.4f}")
  print(f"  Precision: {prec:.4f}")
  print(f"  Recall:    {rec:.4f}")
  print(f"  F1-Score:  {f1:.4f}")
  print(f"  AUC-ROC:   {auc:.4f}")
  print("=" * 45)

  return {"accuracy": acc, "precision": prec, "recall": rec, "f1": f1, "auc": auc}

"""# RESNET-18"""

# Experiment 1 and 2: ResNet-18 pretrained on ImageNet

def get_resnet18(num_classes=2):
    model = models.resnet18(weights=models.ResNet18_Weights.IMAGENET1K_V1)
    in_features = model.fc.in_features  # 512
    model.fc = nn.Sequential(
        nn.Dropout(p=0.5),
        nn.Linear(in_features, num_classes)
    )
    return model.to(device)

resnet = get_resnet18()

optimizer = torch.optim.Adam(resnet.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss(weight=class_weights.to(device))
scheduler = torch.optim.lr_scheduler.MultiStepLR(optimizer, milestones=[10,25], gamma=0.1)

# Experiment 3: no pretrained weights

def get_resnet18_scratch(num_classes=2):
    model = models.resnet18(weights=None)
    in_features = model.fc.in_features  # 512
    model.fc = nn.Sequential(
        nn.Dropout(p=0.5),
        nn.Linear(in_features, num_classes)
    )
    return model.to(device)

resnet_scratch = get_resnet18_scratch()

optimizer = torch.optim.Adam(resnet_scratch.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss(weight=class_weights.to(device))
scheduler = torch.optim.lr_scheduler.MultiStepLR(optimizer, milestones=[10,25], gamma=0.1)

# TorchView Image of ResNet-18 architecture
images, labels, _ = next(iter(train_loader))
resnet_graph = draw_graph(
    resnet_scratch,
    input_size=images.shape,   # (8, 3, 224, 224)
    expand_nested=True,
    roll=True,
    device=device
)
resnet_graph.visual_graph.render(
    "/content/drive/MyDrive/BSC THESIS ALZHEIMERS/resnet18_architorchview",
    format="png"
)
resnet_graph.visual_graph

# Training ResNet-18 From Scratch

RESNET_SCRATCH_SAVE = "/content/drive/MyDrive/BSC THESIS ALZHEIMERS/best_resnet18_scratch.pth"

history_resnet_scratch = train_model(
    model        = resnet_scratch,
    train_loader = train_loader,
    val_loader   = val_loader,
    criterion    = criterion,
    scheduler    = scheduler,
    optimizer    = optimizer,
    num_epochs   = 25, # Experiment 1 and 2 had 50 epochs and patience = 7
    save_path    = RESNET_SCRATCH_SAVE
)

print("\n── ResNet-18 (scratch) Test Results ──")
resnet_scratch_metrics = evaluate_model(resnet_scratch, test_loader, RESNET_SCRATCH_SAVE, device)

"""#MEDVIT

"""

# Train from scratch: no pretrained weights (Experiment 1 onward)
def get_medvit(num_classes=2):
    net = MedViT(
        stem_chs     = [64, 32, 64],
        depths       = [3, 4, 20, 3],
        path_dropout = 0.2,
        num_classes  = num_classes  # directly 2, no head replacement needed
    ).to(device)
    return net

# Hyperparameter tuning of learning rate and weight decay
# Since batch size already set to 8 and optimizer and loss
# Must be equal to ResNet for fair comparison

def objective(trial):
    lr = trial.suggest_categorical('lr', [1e-4, 5e-4, 1e-3])
    wd = trial.suggest_categorical('weight_decay', [1e-5, 1e-4, 1e-3])


    # rebuild loader with this batch size
    train_ds = OASISDataset(train_subjs, DATASET_ROOT, transform=train_transforms)
    val_ds   = OASISDataset(val_subjs,   DATASET_ROOT, transform=val_test_transforms)
    t_loader = DataLoader(train_ds, batch_size=8, shuffle=True,  num_workers=2)
    v_loader = DataLoader(val_ds,   batch_size=8, shuffle=False, num_workers=2)

    model     = get_medvit()
    criterion = nn.CrossEntropyLoss(weight=class_weights.to(device))
    optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=wd)

    best_val_loss = float('inf')
    patience_count = 0

    for epoch in range(20):  # shorter search epochs
        model.train()
        for inputs, labels, _ in t_loader:
            inputs, labels = inputs.to(device), labels.to(device)
            optimizer.zero_grad()
            loss = criterion(model(inputs), labels)
            loss.backward()
            optimizer.step()

        model.eval()
        val_loss = 0
        with torch.no_grad():
            for inputs, labels, _ in v_loader:
                inputs, labels = inputs.to(device), labels.to(device)
                val_loss += criterion(model(inputs), labels).item() * inputs.size(0)
        val_loss /= len(val_ds)

        trial.report(val_loss, epoch)
        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            patience_count = 0
        else:
            patience_count += 1
            if patience_count >= 5:
                break

    return best_val_loss

study = optuna.create_study(direction='minimize',
                             pruner=optuna.pruners.MedianPruner())
study.optimize(objective, n_trials=15)

print("Best hyperparameters:", study.best_params)

# TorchView image of MedViT architecture
medvit_graph = draw_graph(
    medvit,
    input_size=images.shape,   # (8, 3, 224, 224)
    expand_nested=True,
    roll=True,
    device=device
)
medvit_graph.visual_graph.render(
    "/content/drive/MyDrive/BSC THESIS ALZHEIMERS/medvit_architecture",
    format="png"
)
medvit_graph.visual_graph

# Experiment 3 : MedViT from scratch no early stopping and 25 epochs
medvit = get_medvit()

criterion = nn.CrossEntropyLoss(weight=class_weights.to(device))
# Values found with optuna hyperparameter tuning
optimizer_vit = torch.optim.Adam(medvit.parameters(),lr=0.0005,weight_decay=1e-5)
scheduler_vit = torch.optim.lr_scheduler.MultiStepLR(optimizer_vit, milestones=[10, 20], gamma=0.1)

MEDVIT_SAVE = "/content/drive/MyDrive/BSC THESIS ALZHEIMERS/best3_medvit.pth"

history_medvit = train_model(
    medvit,
    train_loader,
    val_loader,
    criterion,
    optimizer_vit,
    scheduler=scheduler_vit,
    num_epochs=25, # Experiment 1 and 2 had 50 epochs and patience = 7
    save_path=MEDVIT_SAVE
)

print("\n── MedViT Test Results ──")
medvit_metrics = evaluate_model(medvit, test_loader, MEDVIT_SAVE, device)

"""# Training Curves"""

# Image 5 - Experiment 1 (early stopping, ResNet pretrained and MedVit from scratch)
# Training curves

def plot_training_curves(history_resnet, history_medvit):
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    fig.suptitle("Training Curves: ResNet-18 vs MedViT", fontsize=15, fontweight="bold")

    epochs_resnet = range(1, len(history_resnet["train_loss"]) + 1)
    epochs_medvit = range(1, len(history_medvit["train_loss"]) + 1)

    # ── Loss ──
    axes[0].plot(epochs_resnet, history_resnet["train_loss"], 'b-',  label="ResNet-18 Train")
    axes[0].plot(epochs_resnet, history_resnet["val_loss"],   'b--', label="ResNet-18 Val")
    axes[0].plot(epochs_medvit, history_medvit["train_loss"], 'r-',  label="MedViT Train")
    axes[0].plot(epochs_medvit, history_medvit["val_loss"],   'r--', label="MedViT Val")
    axes[0].set_title("Loss", fontsize=13)
    axes[0].set_xlabel("Epoch")
    axes[0].set_ylabel("Loss")
    axes[0].legend()
    axes[0].grid(True)

    # ── Accuracy ──
    axes[1].plot(epochs_resnet, history_resnet["train_acc"], 'b-',  label="ResNet-18 Train")
    axes[1].plot(epochs_resnet, history_resnet["val_acc"],   'b--', label="ResNet-18 Val")
    axes[1].plot(epochs_medvit, history_medvit["train_acc"], 'r-',  label="MedViT Train")
    axes[1].plot(epochs_medvit, history_medvit["val_acc"],   'r--', label="MedViT Val")
    axes[1].set_title("Accuracy", fontsize=13)
    axes[1].set_xlabel("Epoch")
    axes[1].set_ylabel("Accuracy")
    axes[1].legend()
    axes[1].grid(True)

    plt.tight_layout()
    plt.savefig("/content/drive/MyDrive/BSC THESIS ALZHEIMERS/training_curves.png", dpi=150)
    plt.show()
    print("Saved to Drive ✓")

plot_training_curves(history_resnet, history_medvit)

# Image 6a for thesis: training curves of Experiment 3 (RESNET)

def plot_training_curves(history_resnet_scratch):
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    fig.suptitle("Training Curves: ResNet-18", fontsize=15, fontweight="bold")

    epochs_resnet = range(1, len(history_resnet_scratch["train_loss"]) + 1)

    # ── Loss ──
    axes[0].plot(epochs_resnet, history_resnet_scratch["train_loss"], 'b-',  label="ResNet-18 Train")
    axes[0].plot(epochs_resnet, history_resnet_scratch["val_loss"],   'b--', label="ResNet-18 Val")
    axes[0].set_title("Loss", fontsize=13)
    axes[0].set_xlabel("Epoch")
    axes[0].set_ylabel("Loss")
    axes[0].legend()
    axes[0].grid(True)

    # ── Accuracy ──
    axes[1].plot(epochs_resnet, history_resnet_scratch["train_acc"], 'b-',  label="ResNet-18 Train")
    axes[1].plot(epochs_resnet, history_resnet_scratch["val_acc"],   'b--', label="ResNet-18 Val")
    axes[1].set_title("Accuracy", fontsize=13)
    axes[1].set_xlabel("Epoch")
    axes[1].set_ylabel("Accuracy")
    axes[1].legend()
    axes[1].grid(True)

    plt.tight_layout()
    plt.savefig("/content/drive/MyDrive/BSC THESIS ALZHEIMERS/resnetScratch.png", dpi=150)
    plt.show()


plot_training_curves(history_resnet_scratch)

# Image 6b for thesis: training curves of Experiment 3 (MEDVIT)

def plot_training_curves(history_medvit):
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    fig.suptitle("Training Curves: MedViT", fontsize=15, fontweight="bold")

    epochs_medvit = range(1, len(history_medvit["train_loss"]) + 1)

    # ── Loss ──
    axes[0].plot(epochs_medvit, history_medvit["train_loss"], 'r-',  label="MedViT Train")
    axes[0].plot(epochs_medvit, history_medvit["val_loss"],   'r--', label="MedViT Val")
    axes[0].set_title("Loss", fontsize=13)
    axes[0].set_xlabel("Epoch")
    axes[0].set_ylabel("Loss")
    axes[0].legend()
    axes[0].grid(True)

    # ── Accuracy ──
    axes[1].plot(epochs_medvit, history_medvit["train_acc"], 'r-',  label="MedViT Train")
    axes[1].plot(epochs_medvit, history_medvit["val_acc"],   'r--', label="MedViT Val")
    axes[1].set_title("Accuracy", fontsize=13)
    axes[1].set_xlabel("Epoch")
    axes[1].set_ylabel("Accuracy")
    axes[1].legend()
    axes[1].grid(True)

    plt.tight_layout()
    plt.savefig("/content/drive/MyDrive/BSC THESIS ALZHEIMERS/medvit25ep.png", dpi=150)
    plt.show()
    print("Saved to Drive ✓")

plot_training_curves(history_medvit)

"""# GRAD-Cams"""

def show_gradcam(model, checkpoint_path, dataset, device, title, target_layers):
    model.load_state_dict(torch.load(checkpoint_path, map_location=device, weights_only=False))
    model.eval()

    cam = GradCAM(model=model, target_layers=target_layers)

    # 2 dementia + 2 non-dementia
    dem_indices    = [i for i in range(len(dataset)) if dataset[i][1] == 1][:2]
    nondem_indices = [i for i in range(len(dataset)) if dataset[i][1] == 0][:2]
    indices = dem_indices + nondem_indices

    fig, axes = plt.subplots(4, 3, figsize=(12, 16))
    fig.suptitle(f"Grad-CAM — {title}", fontsize=14, fontweight="bold")

    for row, idx in enumerate(indices):
        img_tensor, label, subj = dataset[idx]
        input_tensor = img_tensor.unsqueeze(0).to(device)

        with torch.no_grad():
            output = model(input_tensor)
            pred = torch.argmax(output, 1).item()

        targets = [ClassifierOutputTarget(pred)]
        grayscale_cam = cam(input_tensor=input_tensor, targets=targets)[0]

        img_np = img_tensor.permute(1, 2, 0).numpy()
        img_np = (img_np - img_np.min()) / (img_np.max() - img_np.min())
        cam_image = show_cam_on_image(img_np.astype(np.float32), grayscale_cam, use_rgb=True)

        label_str = "Dementia"     if label == 1 else "Non-Dementia"
        pred_str  = "Dementia"     if pred  == 1 else "Non-Dementia"

        axes[row, 0].imshow(img_np, cmap="gray")
        axes[row, 0].set_title(f"Original\nTrue: {label_str}", fontsize=10)
        axes[row, 0].axis("off")
        axes[row, 1].imshow(grayscale_cam, cmap="jet")
        axes[row, 1].set_title("CAM heatmap", fontsize=10)
        axes[row, 1].axis("off")
        axes[row, 2].imshow(cam_image)
        axes[row, 2].set_title(f"Overlay\nPred: {pred_str}", fontsize=10)
        axes[row, 2].axis("off")

    plt.tight_layout()
    save_path = f"/content/drive/MyDrive/BSC THESIS ALZHEIMERS/gradcam_{title.replace('-','').replace(' ','_')}_v2.png"
    plt.savefig(save_path, dpi=150)
    plt.show()
    print(f"Saved: {save_path}")

# Run ResNet
show_gradcam(
    model         = resnet,
    checkpoint_path = RESNET_SAVE,
    dataset       = test_dataset,
    device        = device,
    title         = "ResNet-18",
    target_layers = [resnet.layer4[-1]]
)

# Run MedViT
# since MedViT has no standard attention map export, we use Grad-CAM
# on its last norm layer (standard approach from the paper)
show_gradcam(
    model         = medvit,
    checkpoint_path = MEDVIT_SAVE,
    dataset       = test_dataset,
    device        = device,
    title         = "MedViT",
    target_layers = [medvit.norm]
)

"""# Confusion matrices

"""

def plot_confusion_matrix(model, checkpoint_path, test_loader, device, title):
    model.load_state_dict(torch.load(checkpoint_path, map_location=device, weights_only=False))
    model.eval()

    all_labels = []
    all_preds  = []

    with torch.no_grad():
        for inputs, labels, _ in test_loader:
            inputs = inputs.to(device)
            outputs = model(inputs)
            _, preds = torch.max(outputs, 1)
            all_labels.extend(labels.numpy())
            all_preds.extend(preds.cpu().numpy())

    cm = confusion_matrix(all_labels, all_preds)
    disp = ConfusionMatrixDisplay(cm, display_labels=["Non-Dementia", "Dementia"])
    fig, ax = plt.subplots(figsize=(6, 5))
    disp.plot(ax=ax, colorbar=False, cmap="Blues")
    ax.set_title(title, fontsize=13, fontweight="bold")
    plt.tight_layout()
    plt.savefig(f"/content/drive/MyDrive/BSC THESIS ALZHEIMERS/cm_{title.replace(' ', '_')}.png", dpi=150)
    plt.show()

# Carica i checkpoint e chiama la funzione
plot_confusion_matrix(resnet_scratch, RESNET_SCRATCH_SAVE, test_loader, device, "ResNet-18 From Scratch")
plot_confusion_matrix(medvit, MEDVIT_SAVE, test_loader, device, "MedViT From Scratch")